# Databricks notebook source
# /// script
# [tool.databricks.environment]
# environment_version = "2"
# ///
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# DBTITLE 1,Cell 2
from pyspark import pipelines as dp
from pyspark.sql.functions import col, sum, countDistinct, avg

spark.sql("USE CATALOG `lakeflow_pipeline`")

# COMMAND ----------

# DBTITLE 1,Create a Orders Table In Bronze Schema
@dp.table(
    name="lakeflow_pipeline.1_bronze_db.tb_stre_orders_bronze",
    comment="Bronze streaming table ingesting orders from JSON files"
)
def tb_stre_orders_bronze():
    return (
        spark.readStream.format("cloudFiles")
        .option("cloudFiles.format", "json")
        .load("/Volumes/lakeflow_pipeline/default/data/orders/")
        .selectExpr(
            "*",
            "_metadata.file_name as file_name",
            "_metadata.file_path as file_path",
            "_metadata.file_modification_time as file_modification_time",
            "current_timestamp() as ingestion_ts"
        )
    )

# COMMAND ----------

# DBTITLE 1,Create a order silver table from the Bronze stage
@dp.table(
    name="lakeflow_pipeline.2_silver_db.tb_stre_orders_silver",
    comment="Silver streaming table from bronze orders"
)
def tb_stre_orders_silver():
    df = spark.readStream.table("lakeflow_pipeline.1_bronze_db.tb_stre_orders_bronze")
    return (
        df
        .withColumn("order_id", col("order_id").cast("int"))
        .withColumn("order_ts", col("order_ts").cast("timestamp"))
        .withColumn("customer_id", col("customer_id").cast("int"))
        .withColumn("product_id", col("product_id").cast("int"))
        .withColumn("quantity", col("quantity").cast("int"))
        .withColumn("unit_price", col("unit_price").cast("double"))
        .withColumn("discount_pct", col("discount_pct").cast("double"))
        .withColumn("order_amount", col("order_amount").cast("double"))
        .withColumn("final_status", col("final_status").cast("string"))
        .withColumn("category", col("category").cast("string"))
        .withColumn("channel", col("channel").cast("string"))
        .withColumn("product_name", col("product_name").cast("string"))
        .select(
            "order_id", "order_ts", "customer_id", "product_id", "product_name",
            "category", "quantity", "unit_price", "discount_pct", "order_amount",
            "final_status", "channel", "file_name", "ingestion_ts"
        )
    )

# COMMAND ----------

# DBTITLE 1,Cell 5
@dp.materialized_view(
    name="lakeflow_pipeline.3_gold_db.tb_stre_orders_gold",
    comment="Gold materialized view with order aggregations by timestamp and channel"
)
def tb_stre_orders_gold():
    df = spark.read.table("lakeflow_pipeline.2_silver_db.tb_stre_orders_silver")
    return (
        df
        .groupBy("order_ts", "channel")
        .agg(
            sum("order_amount").alias("total_order_amount"),
            countDistinct("order_id").alias("total_orders"),
            countDistinct("customer_id").alias("total_customers"),
            countDistinct("product_id").alias("total_products"),
            avg("discount_pct").alias("avg_discount_pct"),
            avg("unit_price").alias("avg_unit_price"),
            avg("quantity").alias("avg_quantity"),
            avg("order_amount").alias("avg_order_amount")
        )
        .select(
            "order_ts", "channel", "total_order_amount", "total_orders",
            "total_customers", "total_products", "avg_discount_pct",
            "avg_unit_price", "avg_quantity", "avg_order_amount"
        )
    )
